Выполнены задания 6 урока
FixterSpb/JS-2 pull request #7
Opened 2020-08-04 12:35 UTC by FixterSpb

2020-08-04 12:37 UTC, FixterSpb commented on Lesson_6/project/index.html
> +            <cart ref="cart"></cart>
Разметка поиска

2020-08-04 12:38 UTC, FixterSpb commented on Lesson_6/project/js/ProducComp.js
> +            userSearch: '',
userSearch перенес в products

2020-08-04 12:41 UTC, FixterSpb commented on Lesson_6/project/js/ProducComp.js
> +            userSearch: '',
userSearch перенес в products

2020-08-04 12:49 UTC, FixterSpb commented on Lesson_6/project/js/SearchComp.js
> +        }
Метод фильтрации компонента поиска.

2020-08-20 15:19 UTC, Om1X requested changes

2020-08-20 15:19 UTC, Om1X commented on Lesson_6/project/js/SearchComp.js
> +            this.$root.$refs.products.filter();
можно сделать вызов метода, передав в него this.userSearch, избавившись тем самым от одного шага

2020-10-26 07:08 UTC, merged